In [1]:
# ================================
# 📌 Week 1 Project - Environment Monitoring
# Dataset: city_day.csv (Air Quality Data)
# ================================

# Step 1: Import libraries
import pandas as pd
import numpy as np

# Step 2: Load dataset
file_path = "/content/city_day.csv"   # Adjust if path is different
df = pd.read_csv(file_path)

# Step 3: Initial Exploration
print("---- DATASET SHAPE ----")
print(df.shape)

print("\n---- FIRST 5 ROWS ----")
display(df.head())

print("\n---- INFO ----")
print(df.info())

print("\n---- DESCRIBE ----")
print(df.describe(include='all'))

print("\n---- MISSING VALUES ----")
print(df.isnull().sum())

# Step 4: Preprocessing

# ✅ Convert 'Date' column to datetime
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# ✅ Handle missing values
print("\nMissing values BEFORE cleaning:")
print(df.isnull().sum())

# Fill numeric columns with mean, categorical with mode
for col in df.columns:
    if df[col].dtype == 'O':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:  # numeric
        df[col].fillna(df[col].mean(), inplace=True)

print("\nMissing values AFTER cleaning:")
print(df.isnull().sum())

# ✅ Double check datatypes
print("\nUpdated Data Types:")
print(df.dtypes)

# ✅ Final dataset preview
print("\nFinal cleaned dataset preview:")
display(df.head())

---- DATASET SHAPE ----
(29531, 16)

---- FIRST 5 ROWS ----

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

---- INFO ----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB
None

---- DESCRIBE ----
             City        Date         PM2.5          PM10            NO  \
count       29531       29531  24933.000000  18391.000000  25949.000000
unique         26        2009           NaN           NaN           NaN
top     Ahmedabad  2020-06-26           NaN           NaN           NaN
freq         2009          26           NaN           NaN           NaN
mean          NaN         NaN     67.450578    118.127103     17.574730
std           NaN         NaN     64.661449     90.605110     22.785846
min           NaN         NaN      0.040000      0.010000      0.020000
25%           NaN         NaN     28.820000     56.255000      5.630000
50%           NaN         NaN     48.570000     95.680000      9.890000
75%           NaN         NaN     80.590000    149.745000     19.950000
max           NaN         NaN    949.990000   1000.000000    390.680000

                 NO2           NOx           NH3            CO           SO2  \
count   25946.000000  25346.000000  19203.000000  27472.000000  25677.000000
unique           NaN           NaN           NaN           NaN           NaN
top              NaN           NaN           NaN           NaN           NaN
freq             NaN           NaN           NaN           NaN           NaN
mean       28.560659     32.309123     23.483476      2.248598     14.531977
std        24.474746     31.646011     25.684275      6.962884     18.133775
min         0.010000      0.000000      0.010000      0.000000      0.010000
25%        11.750000     12.820000      8.580000      0.510000      5.670000
50%        21.690000     23.520000     15.850000      0.890000      9.160000
75%        37.620000     40.127500     30.020000      1.450000     15.220000
max       362.210000    467.630000    352.890000    175.810000    193.860000

                  O3       Benzene       Toluene        Xylene           AQI  \
count   25509.000000  23908.000000  21490.000000  11422.000000  24850.000000
unique           NaN           NaN           NaN           NaN           NaN
top              NaN           NaN           NaN           NaN           NaN
freq             NaN           NaN           NaN           NaN           NaN
mean       34.491430      3.280840      8.700972      3.070128    166.463581
std        21.694928     15.811136     19.969164      6.323247    140.696585
min         0.010000      0.000000      0.000000      0.000000     13.000000
25%        18.860000      0.120000      0.600000      0.140000     81.000000
50%        30.840000      1.070000      2.970000      0.980000    118.000000
75%        45.570000      3.080000      9.150000      3.350000    208.000000
max       257.730000    455.030000    454.850000    170.370000   2049.000000

       AQI_Bucket
count       24850
unique          6
top      Moderate
freq         8829
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

---- MISSING VALUES ----
City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

Missing values BEFORE cleaning:
City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

Missing values AFTER cleaning:
City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

Updated Data Types:
City                  object
Date          datetime64[ns]
PM2.5                float64
PM10                 float64
NO                   float64
NO2                  float64
NOx                  float64
NH3                  float64
CO                   float64
SO2                  float64
O3                   float64
Benzene              float64
Toluene              float64
Xylene               float64
AQI                  float64
AQI_Bucket            object
dtype: object

Final cleaned dataset preview:

/tmp/ipython-input-2209421676.py:43: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-2209421676.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00,0.02,0.00,166.463581,Moderate
1,Ahmedabad,2015-01-02,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68,5.50,3.77,166.463581,Moderate
2,Ahmedabad,2015-01-03,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80,16.40,2.25,166.463581,Moderate
3,Ahmedabad,2015-01-04,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43,10.14,1.00,166.463581,Moderate
4,Ahmedabad,2015-01-05,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01,18.89,2.78,166.463581,Moderate